apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: {SCAN_NAME}-html-results
  name: {SCAN_NAME}-html-results
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {SCAN_NAME}-html-results
    version: v1
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        app: {SCAN_NAME}-html-results
        version: v1
    spec:
      containers:
      - image: docker.io/rfplay/compliance-reportgen:v1.0
        name: {SCAN_NAME}-html-results
        volumeMounts:
        - mountPath: /opt/nginx/html
          name: results
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: results
          persistentVolumeClaim:
            claimName: {SCAN_NAME}
  triggers:
  - type: ConfigChange
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {SCAN_NAME}-html-results
  name: {SCAN_NAME}-html-results
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: {SCAN_NAME}-html-results
  sessionAffiniity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
  labels:
    app: {SCAN_NAME}-html-results
  name: {SCAN_NAME}-html-results
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: {SCAN_NAME}-html-results
    weight: 100
  wildcardPolicy: None
